name: "Pack - Electron App"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

on:
  push:
    branches:
      - "feat/pack-tauriapp-workflow"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/pack-electron.yml"

jobs:
  tauri:
    defaults:
      run:
        working-directory: ./src
    strategy:
      fail-fast: false
      matrix:
        include:
          #- platform: "macos-latest" # for Arm based macs (M1 and above).
          #  args: "--target aarch64-apple-darwi -c src-tauri/tauri.conf.mac-arm64.json5n"
          #- platform: "macos-latest" # for Intel based macs.
          #  args: "--target x86_64-apple-darwin -c src-tauri/tauri.conf.mac-x64.json5"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""
          #- platform: "windows-latest"
          #  args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: 🧲 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 🧲 Setup .NET 7
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Install frontend dependencies (SPA)
        working-directory: "src/Apps/NetPad.Apps.App/App"
        run: npm install

      - name: Install frontend dependencies (SPA)
        working-directory: "src/Apps/NetPad.Apps.App/ElectronHostHook"
        run: npm install

      - name: Package for Linux
        working-directory: "src/Apps/NetPad.Apps.App"
        run: |
          dotnet restore
          dotnet tool install ElectronNET.CLI -g --version 23.6.1.0
          electronize build /target linux /manifest electron.manifest.js /PublishSingleFile false
          electronize build /target win /manifest electron.manifest.js /PublishSingleFile false

      - name: List build files
        working-directory: "src/Apps/NetPad.Apps.App/bin/Desktop"
        run: ls -al
        shell: bash

      - name: 'Upload Bundled Packages'
        uses: actions/upload-artifact@v4
        with:
          name: netpad_0.8.0.bundles
          path: |
            src/Apps/NetPad.Apps.App/bin/Desktop/netpad-0.8.0-linux-x64.zip
            src/Apps/NetPad.Apps.App/bin/Desktop/netpad-0.8.0-linux-amd64.snap
            src/Apps/NetPad.Apps.App/bin/Desktop/netpad-0.8.0-linux-x86_64.AppImage
            src/Apps/NetPad.Apps.App/bin/Desktop/netpad-0.8.0-linux-x86_64.deb
            src/Apps/NetPad.Apps.App/bin/Desktop/netpad-0.8.0-linux-x86_64.rpm
            src/Apps/NetPad.Apps.App/bin/Desktop/netpad-0.8.0-linux-x86_64.pacman
          retention-days: 1
          if-no-files-found: warn
